// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: ipaddress.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IPAddressService_AssignAddress_FullMethodName  = "/ipman.IPAddressService/AssignAddress"
	IPAddressService_ReleaseAddress_FullMethodName = "/ipman.IPAddressService/ReleaseAddress"
	IPAddressService_ListAddresses_FullMethodName  = "/ipman.IPAddressService/ListAddresses"
	IPAddressService_UpdateAddress_FullMethodName  = "/ipman.IPAddressService/UpdateAddress"
)

// IPAddressServiceClient is the client API for IPAddressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IPAddressServiceClient interface {
	AssignAddress(ctx context.Context, in *AssignAddressRequest, opts ...grpc.CallOption) (*AssignAddressResponse, error)
	ReleaseAddress(ctx context.Context, in *ReleaseAddressRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListAddresses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAddressesResponse, error)
	UpdateAddress(ctx context.Context, in *UpdateAddressRequest, opts ...grpc.CallOption) (*UpdateAddressResponse, error)
}

type iPAddressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIPAddressServiceClient(cc grpc.ClientConnInterface) IPAddressServiceClient {
	return &iPAddressServiceClient{cc}
}

func (c *iPAddressServiceClient) AssignAddress(ctx context.Context, in *AssignAddressRequest, opts ...grpc.CallOption) (*AssignAddressResponse, error) {
	out := new(AssignAddressResponse)
	err := c.cc.Invoke(ctx, IPAddressService_AssignAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPAddressServiceClient) ReleaseAddress(ctx context.Context, in *ReleaseAddressRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IPAddressService_ReleaseAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPAddressServiceClient) ListAddresses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAddressesResponse, error) {
	out := new(ListAddressesResponse)
	err := c.cc.Invoke(ctx, IPAddressService_ListAddresses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPAddressServiceClient) UpdateAddress(ctx context.Context, in *UpdateAddressRequest, opts ...grpc.CallOption) (*UpdateAddressResponse, error) {
	out := new(UpdateAddressResponse)
	err := c.cc.Invoke(ctx, IPAddressService_UpdateAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IPAddressServiceServer is the server API for IPAddressService service.
// All implementations must embed UnimplementedIPAddressServiceServer
// for forward compatibility
type IPAddressServiceServer interface {
	AssignAddress(context.Context, *AssignAddressRequest) (*AssignAddressResponse, error)
	ReleaseAddress(context.Context, *ReleaseAddressRequest) (*emptypb.Empty, error)
	ListAddresses(context.Context, *emptypb.Empty) (*ListAddressesResponse, error)
	UpdateAddress(context.Context, *UpdateAddressRequest) (*UpdateAddressResponse, error)
	mustEmbedUnimplementedIPAddressServiceServer()
}

// UnimplementedIPAddressServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIPAddressServiceServer struct {
}

func (UnimplementedIPAddressServiceServer) AssignAddress(context.Context, *AssignAddressRequest) (*AssignAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignAddress not implemented")
}
func (UnimplementedIPAddressServiceServer) ReleaseAddress(context.Context, *ReleaseAddressRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseAddress not implemented")
}
func (UnimplementedIPAddressServiceServer) ListAddresses(context.Context, *emptypb.Empty) (*ListAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAddresses not implemented")
}
func (UnimplementedIPAddressServiceServer) UpdateAddress(context.Context, *UpdateAddressRequest) (*UpdateAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAddress not implemented")
}
func (UnimplementedIPAddressServiceServer) mustEmbedUnimplementedIPAddressServiceServer() {}

// UnsafeIPAddressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IPAddressServiceServer will
// result in compilation errors.
type UnsafeIPAddressServiceServer interface {
	mustEmbedUnimplementedIPAddressServiceServer()
}

func RegisterIPAddressServiceServer(s grpc.ServiceRegistrar, srv IPAddressServiceServer) {
	s.RegisterService(&IPAddressService_ServiceDesc, srv)
}

func _IPAddressService_AssignAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAddressServiceServer).AssignAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAddressService_AssignAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAddressServiceServer).AssignAddress(ctx, req.(*AssignAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPAddressService_ReleaseAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAddressServiceServer).ReleaseAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAddressService_ReleaseAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAddressServiceServer).ReleaseAddress(ctx, req.(*ReleaseAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPAddressService_ListAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAddressServiceServer).ListAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAddressService_ListAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAddressServiceServer).ListAddresses(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPAddressService_UpdateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAddressServiceServer).UpdateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAddressService_UpdateAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAddressServiceServer).UpdateAddress(ctx, req.(*UpdateAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IPAddressService_ServiceDesc is the grpc.ServiceDesc for IPAddressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IPAddressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ipman.IPAddressService",
	HandlerType: (*IPAddressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignAddress",
			Handler:    _IPAddressService_AssignAddress_Handler,
		},
		{
			MethodName: "ReleaseAddress",
			Handler:    _IPAddressService_ReleaseAddress_Handler,
		},
		{
			MethodName: "ListAddresses",
			Handler:    _IPAddressService_ListAddresses_Handler,
		},
		{
			MethodName: "UpdateAddress",
			Handler:    _IPAddressService_UpdateAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ipaddress.proto",
}
